# applications/otel-collector/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: 0.72.1
    helm:
      values: |
        mode: deployment
        image:
          repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib
          tag: "0.96.0"
        config:
          exporters:
            logging:
              loglevel: info
          receivers:
            otlp:
              protocols:
                grpc: {}
                http: {}
          service:
            pipelines:
              traces:
                receivers: [otlp]
                processors: []
                exporters: [logging]
  destination:
    server: https://kubernetes.default.svc
    namespace: otel-collector
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
